apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rollupdate-rc-v1
spec:
  replicas: 3
  selector:
    app: demo-rollupdate-rc
  template:
    metadata:
      name: demo-rollupdate-rc-pod
      labels:
        app: demo-rollupdate-rc
    spec:
      containers:
      - image: demo-rollupdate-image:v1
        imagePullPolicy: Never
        name: demo-rollupdate-rc-pod-container
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-rollupdate-service
spec:
  type: NodePort
  selector:
    app: demo-rollupdate-rc
  ports:
  - name: http
    port: 80
    # The Service "demo-rollupdate-service" is invalid: spec.ports[0].nodePort: Invalid value: 29980: provided port is not in the valid range. The range of valid ports is 30000-3276
    nodePort: 30180
    targetPort: http
